name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.4, 8.3, 8.2 ]
        database: [ mysql, mariadb, pgsql, sqlite, sqlsrv, singlestore ]
        #        release: [ stable, lowest ]
        release: [ stable ]
        include:
          - php: 8.4
            database: mysql
            release: stable
            coverage: true

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: ~/.cache/composer/files
          key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Start database container
        if: matrix.database != 'sqlite'
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up --wait ${{ matrix.database }}

      - name: Create SQL Server database
        if: matrix.database == 'sqlsrv'
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml exec sqlsrv /opt/mssql-tools18/bin/sqlcmd -C -S 127.0.0.1 -U sa -P Password! -Q 'CREATE DATABASE [test]'

      - name: Install dependencies
        run: |
          SERVICE="php${{ matrix.php }}"
          docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm "$SERVICE" \
            composer update --no-interaction --no-progress --prefer-dist --prefer-${{ matrix.release }}

      - name: Run tests
        env:
          COVERAGE_ARGS: ${{ matrix.coverage && '--coverage-clover=coverage.xml' || '' }}
          DB_CONNECTION: ${{ matrix.database }}
        run: |
          SERVICE="php${{ matrix.php }}"
          if [ "${{ matrix.coverage && 'true' || 'false' }}" = "true" ]; then
            SERVICE="${SERVICE}-xdebug"
          fi

          docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm -e DB_CONNECTION="$DB_CONNECTION" "$SERVICE" \
            vendor/bin/pest --ci $COVERAGE_ARGS

      - name: Upload code coverage
        if: matrix.coverage
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml

      - name: Shutdown containers
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml down --volumes --remove-orphans
